### ISSUE TITLE
Downloads not marked complete when retried + resumed

### ISSUE THREAD

**Issue by jghodd** [jjk-jacky/kalu#45]
Downloads are no longer being marked blue if a download timeout + retry + resume occurs, even though the download completes and the package is correctly upgraded/installed. It looks like the problem manifests in the line:

`dl_done = (cur_size + tot_size == dl_size);`

from updater.c -> on_event_pkgdownload_done().

I'm guessing either cur_size or tot_size is getting reset when there's a retry which causes a false result to be assigned to dl_done.

**Comment by jjk-jacky** [comment]
Right, there was a mistake and the total download size was added on
failure, so afterwards the values wouldn't match indeed. This is all a
bit more complicated also because we're trying to handle things right
on multiple downloads per package in case of deltas...

Anyhow, I think it should work now, with the commit just push to branch
fix-45 -- please try it and let me know.

**Comment by jghodd** [comment]
I know this is going to be a little frustrating, but this didn't fix the issue. I added logging of cur_size, tot_size and dl_size after the dl_done assignment and I'm seeing this (for example):

cur_size: 585232 ; tot_size: 0 ; dl_size: 1841828

I'm also seeing that tot_size is consistently 0, even when the download succeeds in one shot (although in that case cur_size does match dl_size).

Sorry, bud.

**Comment by jghodd** [comment]
Here's a more complete example of a timeout + resume:

```
Error: failed retrieving file 'telepathy-kde-integration-module-15.12.3-1-x86_64.pkg.tar.xz' from mirrors.acm.wpi.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'telepathy-kde-integration-module-15.12.3-1-x86_64.pkg.tar.xz' from mirrors.advancedhosters.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
cur_size: 26810 ; tot_size: 0 ; dl_size: 101456
```

This download completed and was installed successfully.

**Comment by jjk-jacky** [comment]
Right, my bad; I thought a pkgdownload_failed event would occur, but a
quick read of the ALPM code reminded me that that isn't the case. I've
pushed a new version of the fix, one that hopefully should work
(better) now.

Please give it a try & let me know.

**Comment by jghodd** [comment]
Looks like a good fix in the code, but I'm not timing out my downloads at the moment, so I can;t test your fix - at least until later (my internet bandwidth usually bottoms out between 7pm and 1am). Anyway, I'll check it again this evening and let you know how it does.

The fix does look like it'll work though...

**Comment by jghodd** [comment]
Ok - massaged a big update to occur to get the timeouts. Everything looked good, although I was a little stumped by my logging numbers (at the bottom):

`Downloading packages...
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirrors.acm.wpi.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirrors.advancedhosters.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirrors.aggregate.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from archlinux.surlyjake.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirror.atlantic.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from ca.us.mirror.archlinux-br.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirrors.cat.pdx.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirror.cc.columbia.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from cosmos.cites.illinois.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirror.cs.pitt.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirror.es.its.nyu.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirror1.gaw.solutions : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirror2.gaw.solutions : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirror3.gaw.solutions : transfer closed with 255484594 bytes remaining to read
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirrors.gigenet.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirror.grig.io : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from www.gtlib.gatech.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirror.ancl.hawaii.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirror.htnshost.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from arch.mirrors.ionfish.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirror.jmu.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from jordynsblog.tk : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
Error: failed retrieving file 'netbeans-8.1-2-any.pkg.tar.xz' from mirrors.kernel.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
cur_size: 239524250 ; tot_size: 36637506 ; dl_size: 276161756
Processing package changes...
Package upgraded: netbeans (8.1-1 -> 8.1-2)`

cur_size + tot_size is definitely >= dl_size - perhaps you could explain the discrepancy so I understand what happened there...?

**Comment by jjk-jacky** [comment]
> cur_size: 239524250 ; tot_size: 36637506 ; dl_size: 276161756
>
> cur_size + tot_size is definitely >= dl_size - perhaps you could
> explain the discrepancy so I understand what happened there...?

Not sure I follow... 239524250 + 36637506 = 276161756
looks exactly like what you'd expect to me?

**Comment by jghodd** [comment]
Sorry - I had added an Edit... you probably didn;t catch it before replying.

**Comment by jghodd** [comment]
![kalu-kde-fix-45-screen](https://cloud.githubusercontent.com/assets/17838067/13858561/96e6ee38-ec55-11e5-82bc-659f4e34dd5f.png)

**Comment by jjk-jacky** [comment]
Yeah sorry, seems I don't get emails on edits so I didn't see that.

As for an explanation, this is implementation details but here it goes: when a download starts, the downloaded size is stored as cur_size, which comes from ALPM (and cURL behind it). However, if there's a failure and ALPM switches/resumes from another mirror, the cur_size would be reset to zero (as for cURL this is a new download), so to keep track kalu adds the value into tot_size.

In the end, assuming one download eventually succeeds, cur_size is what was downloaded from that last mirror, and tot_size what was done from the one(s) before it.
dl_size is the expected size to be downloaded, as reported from ALPM before any download took place. So in the end after a pkgdownload_done event, if cur_size + tot_size == dl_size, then everything is completed as expected.
(Noting that this would normally always be the case anyway, except when using deltas (i.e. more than one file for a single package), which is why this is required in the first place.)

**Comment by jghodd** [comment]
Cool. Thanks for the explanation - makes total sense.

I think we can say it's fixed - left you a screen shot so you can see the blue marking on the successful download.

Thanks for getting to this as quickly as you did. Much appreciated.
