### ISSUE TITLE
Kalu gets stuck on "Checking/updating in progress..."

### ISSUE THREAD

**Issue by protist** [jjk-jacky/kalu#70]
A few times a week, kalu gets stuck. The icon is flashing, and hovering shows a pop-up saying

    [kalu] Checking/updating in progress...

There is nothing in the terminal, except the "normal" GTK errors:
```
(kalu:20654): Gtk-CRITICAL **: 08:00:52.804: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed

(kalu:20654): Gtk-CRITICAL **: 08:00:53.224: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed

(kalu:20654): Gtk-CRITICAL **: 08:00:53.645: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed
```

Occasionally, kalu will then give an error message saying that it fails to connect, and then will reset. Mostly however, it stays stuck indefinitely. I have to SIGKILL, and restart kalu. I'm happy to provide more debugging information, but I'm not sure how to go about this.

Possibly relevant, I use a VPN via NetworkManager. After resuming from suspend, I have normal network connectivity after a few seconds, but the VPN then takes another few seconds to connect. This creates problems for things like Firefox. If I connect to a web page after initial connectivity, loading can stall after the VPN turns on. I'm unsure if kalu has similar issues if it is checking for updates when the VPN turns on. Either way, I presume that kalu's timeout should fix this in theory.

I'm using kalu-kde 4.3.0-1 from the AUR, which is kalu compiled with `--enable-status-notifier` and depending on `statusnotifier`. I'm using KDE Plasma, and my Arch install is up-to-date. I've been experiencing this issue for a few months now.

**Comment by jjk-jacky** [comment]
> (kalu:20654): Gtk-CRITICAL **: 08:00:52.804:
> gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON
> (status_icon)' failed

I believe this is completely unrelated, and should be fixed on branch
next in github BTW.


> Occasionally, kalu will then give an error message saying that it
> fails to connect, and then will reset. Mostly however, it stays stuck
> indefinitely. I have to SIGKILL, and restart kalu. I'm happy to
> provide more debugging information, but I'm not sure how to go about
> this.

Well, if the icon is still flashing as you way, clearly kalu isn't
crashed/stucked or anything. It sounds like there's a connection that
it's waiting for, and for some reason never dies/times out... not sure
why though.

If you could reproduce it while running it with --debug it might
indicate at least during which check(s) it happens (RSS/news, upgrades,
AUR...) but really they should all fail/time out at some point.

**Comment by protist** [comment]
Thank you for the quick response.

> I believe this is completely unrelated, and should be fixed on branch next in github BTW.

Brilliant. Thank you.

> clearly kalu isn't crashed/stucked or anything

Ah yes, fair enough. My language was imprecise. Normally, SIGTERM can terminate kalu. However, when I described kalu as "stuck" above, I need SIGKILL to terminate it.

> If you could reproduce it while running it with --debug

I'll try to catch it with this flag, and report back here.

**Comment by jjk-jacky** [comment]
> Ah yes, fair enough. My language was imprecise. Normally, SIGTERM can
> terminate kalu. However, when I described kalu as "stuck" above, I
> need SIGKILL to terminate it.

Ah right, but that would be by design though, because kalu basically
ignores SIGINT & SIGTERM when it is busy, i.e. running checks or the
updater.

I've pushed a branch abort-checks on github, changing how this is done.
Now SIGINT will abort any running checks (but not cause kalu to exit),
and SIGTERM will abort any running checks and then exit. Note that both
are still basically ignored when the updater is running though.

I've also added a menu item on top of the menu, when checks are
running, to abort them. So, if you can try kalu from this branch, when
it gets "stucked" you can try aborting (send SIGINT or use the new menu
item) and see if that helps. (If not, it would still be good to have
the --debug output, again to get a sense of when this happens.)

I need to add however, that due to a little bug in pacman (libalpm)
once you've aborted checks (doesn't matter how, the menu item simply
raises SIGINT anyways) you'll need to exit kalu & restart it, otherwise
ALPM will just abort for any & all new downloads due to that bug.
Or, you can buid pacman with the patch[1] to fix the issue ;)

Cheers,


[1]
https://lists.archlinux.org/pipermail/pacman-dev/2018-October/022861.html

**Comment by protist** [comment]
> I've pushed a branch
> I've also added a menu item

Brilliant, thank you for that!

Also, kalu stalled again. It looks like it happened this morning, 12 hours ago, so it's definitely beyond a plausible timeout (although the computer was suspended for most of that). The output is below. I stripped out all of the `Gtk-CRITICAL` lines for readability.

I checked my logs, and the computer resumed from suspend at 7:43:31, and then slept again at 8:11:54. I'd say the time at which kalu failed, 14 seconds after suspend, is likely when the VPN turns on again from experience.

```
[22:36:38] state non-busy: disable switch icons
[22:36:38] state non-busy: next auto-checks in 3600 seconds
[07:43:31] state busy: disable next auto-checks
[07:43:31] state busy: switch icons
[07:43:31] drop last_notifs
[07:43:31] downloading https://www.archlinux.org/feeds/news/
[07:43:38] downloaded 12834 bytes
[07:43:38] parsing pacman.conf (/etc/pacman.conf) for options
[07:43:38] config: attempting to read file /etc/pacman.conf
[07:43:38] config: new section 'options'
[07:43:38] config: arch: x86_64
[07:43:38] config: checkspace
[07:43:38] config: verbosepkglists
[07:43:38] config: SigLevel: Required
[07:43:38] config: SigLevel: DatabaseOptional
[07:43:38] config: new section 'core'
[07:43:38] config file /etc/pacman.conf, line 76: including /etc/pacman.d/mirrorlist
[07:43:38] config: attempting to read file /etc/pacman.d/mirrorlist
[07:43:38] config: finished parsing /etc/pacman.d/mirrorlist
[07:43:38] config: new section 'extra'
[07:43:38] config file /etc/pacman.conf, line 79: including /etc/pacman.d/mirrorlist
[07:43:38] config: attempting to read file /etc/pacman.d/mirrorlist
[07:43:38] config: finished parsing /etc/pacman.d/mirrorlist
[07:43:38] config: new section 'community'
[07:43:38] config file /etc/pacman.conf, line 85: including /etc/pacman.d/mirrorlist
[07:43:38] config: attempting to read file /etc/pacman.d/mirrorlist
[07:43:38] config: finished parsing /etc/pacman.d/mirrorlist
[07:43:38] config: new section 'multilib'
[07:43:38] config file /etc/pacman.conf, line 94: including /etc/pacman.d/mirrorlist
[07:43:38] config: attempting to read file /etc/pacman.d/mirrorlist
[07:43:38] config: finished parsing /etc/pacman.d/mirrorlist
[07:43:38] config: finished parsing /etc/pacman.conf
[07:43:38] setting up libalpm
[07:43:38] checking local db /tmp/kalu-R0N7PZ
[07:43:38] ..folder found, getting dbpath
[07:43:38] same dbpath (/var/lib/pacman), re-using
[07:43:38] keeping current /tmp/kalu-R0N7PZ/sync/extra.db
[07:43:38] keeping current /tmp/kalu-R0N7PZ/sync/core.db
[07:43:38] keeping current /tmp/kalu-R0N7PZ/sync/multilib.db
[07:43:38] keeping current /tmp/kalu-R0N7PZ/sync/community.db
[07:43:38] register core
[07:43:38] add server http://mirror.internode.on.net/pub/archlinux/core/os/x86_64 into core
[07:43:38] add server http://ftp.swin.edu.au/archlinux/core/os/x86_64 into core
[07:43:38] add server https://mirror.aarnet.edu.au/pub/archlinux/core/os/x86_64 into core
[07:43:38] add server http://ftp.iinet.net.au/pub/archlinux/core/os/x86_64 into core
[07:43:38] add server http://archlinux.melbourneitmirror.net/core/os/x86_64 into core
[07:43:38] add server http://archlinux.mirror.digitalpacific.com.au/core/os/x86_64 into core
[07:43:38] register extra
[07:43:38] add server http://mirror.internode.on.net/pub/archlinux/extra/os/x86_64 into extra
[07:43:38] add server http://ftp.swin.edu.au/archlinux/extra/os/x86_64 into extra
[07:43:38] add server https://mirror.aarnet.edu.au/pub/archlinux/extra/os/x86_64 into extra
[07:43:38] add server http://ftp.iinet.net.au/pub/archlinux/extra/os/x86_64 into extra
[07:43:38] add server http://archlinux.melbourneitmirror.net/extra/os/x86_64 into extra
[07:43:38] add server http://archlinux.mirror.digitalpacific.com.au/extra/os/x86_64 into extra
[07:43:38] register community
[07:43:38] add server http://mirror.internode.on.net/pub/archlinux/community/os/x86_64 into community
[07:43:38] add server http://ftp.swin.edu.au/archlinux/community/os/x86_64 into community
[07:43:38] add server https://mirror.aarnet.edu.au/pub/archlinux/community/os/x86_64 into community
[07:43:38] add server http://ftp.iinet.net.au/pub/archlinux/community/os/x86_64 into community
[07:43:38] add server http://archlinux.melbourneitmirror.net/community/os/x86_64 into community
[07:43:38] add server http://archlinux.mirror.digitalpacific.com.au/community/os/x86_64 into community
[07:43:38] register multilib
[07:43:38] add server http://mirror.internode.on.net/pub/archlinux/multilib/os/x86_64 into multilib
[07:43:38] add server http://ftp.swin.edu.au/archlinux/multilib/os/x86_64 into multilib
[07:43:38] add server https://mirror.aarnet.edu.au/pub/archlinux/multilib/os/x86_64 into multilib
[07:43:38] add server http://ftp.iinet.net.au/pub/archlinux/multilib/os/x86_64 into multilib
[07:43:38] add server http://archlinux.melbourneitmirror.net/multilib/os/x86_64 into multilib
[07:43:38] add server http://archlinux.mirror.digitalpacific.com.au/multilib/os/x86_64 into multilib
[07:43:38] core is up to date
[07:43:39] extra was updated
[07:43:42] community was updated
[07:43:42] multilib is up to date
[07:43:42] -> flashplugin 31.0.0.108-1 -> 31.0.0.122-1 [dl=7276120; ins=20108288]
[07:43:42] -> pepper-flash 31.0.0.108-1 -> 31.0.0.122-1 [dl=7699312; ins=21662720]
[07:43:42] adding new notif (2 updates available (D: 14.28 MiB; N: 3.00 KiB)) to last_notifs
[07:43:42] showing notif: 2 updates available (D: 14.28 MiB; N: 3.00 KiB)
- <b>flashplugin</b> 31.0.0.108-1 > <b>31.0.0.122-1</b> (D: 6.94 MiB; N: -1024 B)
- <b>pepper-flash</b> 31.0.0.108-1 > <b>31.0.0.122-1</b> (D: 7.34 MiB; N: 4.00 KiB)
--- EOF ---
[07:43:42] new notification: using kalu's icon
[07:43:42] looking for AUR updates
[07:43:42] downloading https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=acroread&arg[]=amarok&arg[]=antimicro&arg[]=apg&arg[]=archlinux-java-run&arg[]=backintime-cli-git&arg[]=backintime-git&arg[]=blast%2B-bin&arg[]=botanicula&arg[]=caffeine-ng&arg[]=clustal-omega&arg[]=coin&arg[]=cropgui&arg[]=dragon-drag-and-drop-git&arg[]=dungeons-of-dredmor&arg[]=emojione-picker-git&arg[]=figtree&arg[]=font-manager&arg[]=fonts-meta-base&arg[]=fonts-meta-extended-lt&arg[]=freecad&arg[]=fslint&arg[]=gtklp&arg[]=gtkpod&arg[]=htslib&arg[]=igv&arg[]=imgur-screenshot-git&arg[]=imwheel&arg[]=inkslides-git&arg[]=invada-studio-plugins-lv2&arg[]=jabref&arg[]=jdownloader2&arg[]=jre&arg[]=kalu-kde&arg[]=krop&arg[]=libgcj17-bin&arg[]=libhashab-git&arg[]=libreoffice-extension-languagetool&arg[]=lingot&arg[]=lorem-ipsum-generator&arg[]=machinarium&arg[]=med&arg[]=memtest86-efi&arg[]=miro-video-converter&arg[]=mutt-ics&arg[]=mutt-vid&arg[]=muttprint&arg[]=neomutt-git&arg[]=nextcloud-client&arg[]=nodejs-imapnotify-git&arg[]=nottoomuch-addresses-git
[07:43:45] downloaded 30895 bytes
[07:43:45] parsing json
[07:43:45] got 51 results
[07:43:45] downloading https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=nvim-r&arg[]=openrct2&arg[]=otf-eau-douce-sans&arg[]=pacolog&arg[]=pdftk-bin&arg[]=perl-extract-url&arg[]=perl-uri-find&arg[]=phyml-mpi&arg[]=pidgin-indicator&arg[]=pidgin-toobars&arg[]=plasma5-applet-awesome-widgets&arg[]=plasma5-applets-network-monitor&arg[]=plasma5-applets-resources-monitor-git&arg[]=printrun&arg[]=puddletag&arg[]=pyqt4-common&arg[]=python-ewmh&arg[]=python-grip&arg[]=python-path-and-address&arg[]=python-poppler-qt5&arg[]=python-pypdf2&arg[]=python2-epub&arg[]=python2-pivy&arg[]=python2-pylzma&arg[]=python2-pyqt4&arg[]=python2-pyside2&arg[]=python2-rarfile&arg[]=python2-shiboken2&arg[]=ripmime&arg[]=samorost2&arg[]=samtools&arg[]=sc-im&arg[]=signal-back-bin&arg[]=soqt&arg[]=statusnotifier&arg[]=stopwatch&arg[]=todotxt&arg[]=ttf-caladea&arg[]=ttf-courier-prime&arg[]=ttf-gelasio-ib&arg[]=ttf-heuristica&arg[]=ttf-impallari-cantora&arg[]=ttf-merriweather&arg[]=ttf-merriweather-sans&arg[]=ttf-opensans&arg[]=ttf-oswald&arg[]=ttf-quintessential
```

**Comment by jjk-jacky** [comment]
> I checked my logs, and the computer resumed from suspend at 7:43:31,
> and then slept again at 8:11:54. I'd say the time at which kalu
> failed, 14 seconds after suspend, is likely when the VPN turns on
> again from experience.

From the log, at 07:43:31 (so when you resumed) kalu starts its checks.
The news are downloaded fine, the updates are also checked without
issue, then comes the AUR check.
A first query is done and results downloaded in a few seconds, then a
second query is done and... nothing. That's 14 seconds after resume, so
when you suspect your VPN to turn on, right?

So maybe your VPN is changing your configuration (routing, etc) and
somehow breaks kalu.

I've pushed some changes on branch abort-checks, during such downloads
kalu should now abort/timeout if the speed goes under 1b/s during 10s
-- so hopefully with this, after about 10s it should now timeout.

Please rebuild kalu from the latest abort-checks and let me know if
that changes anything; Thanks.

Cheers,

**Comment by protist** [comment]
Thank you again.

> That's 14 seconds after resume, so when you suspect your VPN to turn on, right? 

Correct.

> So maybe your VPN is changing your configuration (routing, etc) and somehow breaks kalu.

Yes, that is my interpretation also.

> Please rebuild kalu from the latest abort-checks and let me know if that changes anything; Thanks.

Done. I'll report back when I notice anything again. It's intermittent, and I guess I'm looking for the lack of an error, so if I take a while then it's probably a good thing.

I can report that the `Gtk-CRITICAL` messages are gone, too! Thanks again.

**Comment by protist** [comment]
I *think* it's working. I resumed from sleep, then got a notification ~5 minutes later.
```
[22:44:47] looking for Watched AUR updates
[22:44:47] downloading https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=foo&arg[]=bar&arg[]=baz
[22:49:48] adding new notif (Unable to check for updates of watched AUR packages) to last_notifs
[22:49:48] showing notif: Unable to check for updates of watched AUR packages
Operation timed out after 300328 milliseconds with 0 out of 0 bytes received
--- EOF ---
[22:49:48] new notification: using kalu's icon
[22:49:48] state non-busy: disable switch icons
[22:49:48] state non-busy: next auto-checks in 3600 seconds
```

I'm guessing this is the new timeout?

**Comment by jjk-jacky** [comment]
> I'm guessing this is the new timeout?

Yes, looks like that would be it indeed.

So this should be fixed now, good. Thanks!

**Comment by protist** [comment]
Thank you! I appreciate your excellent support once again!

**Comment by protist** [comment]
I just noticed that this issue has appeared again. Unbeknown to me, Kalu was stuck for a few days. I'm happy to troubleshoot and check times again, but I just thought to mention it here just in case it was an obvious change in the code.

**Comment by protist** [comment]
Well, I'm not sure if I've caught it in the terminal, but I'll post this up anyway. (Please note I'm still getting the GTK errors.)
```
$ kalu --debug
...
[12:35:42] downloaded 1078 bytes
[12:35:42] parsing json
[12:35:42] got 2 results
[12:35:42] state non-busy: disable switch icons
[12:35:42] state non-busy: next auto-checks in 3600 seconds

(kalu:1711): Gtk-CRITICAL **: 12:35:42.618: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed
[13:35:42] state busy: disable next auto-checks
[13:35:42] state busy: switch icons
[13:35:42] drop last_notifs
[13:35:42] downloading https://www.archlinux.org/feeds/news/

(kalu:1711): Gtk-CRITICAL **: 13:35:43.039: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed

(kalu:1711): Gtk-CRITICAL **: 13:35:43.460: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed
[13:35:43] downloaded 13188 bytes
[13:35:43] parsing pacman.conf (/etc/pacman.conf) for options
[13:35:43] config: attempting to read file /etc/pacman.conf
[13:35:43] config: new section 'options'
[13:35:43] config: arch: x86_64
[13:35:43] config: IgnorePkg: zsh-zim-git
[13:35:43] config: checkspace
[13:35:43] config: verbosepkglists
[13:35:43] config: SigLevel: Required
[13:35:43] config: SigLevel: DatabaseOptional
[13:35:43] config: new section 'core'
[13:35:43] config file /etc/pacman.conf, line 77: including /etc/pacman.d/mirrorlist
[13:35:43] config: attempting to read file /etc/pacman.d/mirrorlist
[13:35:43] config: finished parsing /etc/pacman.d/mirrorlist
[13:35:43] config: new section 'extra'
[13:35:43] config file /etc/pacman.conf, line 80: including /etc/pacman.d/mirrorlist
[13:35:43] config: attempting to read file /etc/pacman.d/mirrorlist
[13:35:43] config: finished parsing /etc/pacman.d/mirrorlist
[13:35:43] config: new section 'community'
[13:35:43] config file /etc/pacman.conf, line 86: including /etc/pacman.d/mirrorlist
[13:35:43] config: attempting to read file /etc/pacman.d/mirrorlist
[13:35:43] config: finished parsing /etc/pacman.d/mirrorlist
[13:35:43] config: new section 'multilib'
[13:35:43] config file /etc/pacman.conf, line 95: including /etc/pacman.d/mirrorlist
[13:35:43] config: attempting to read file /etc/pacman.d/mirrorlist
[13:35:43] config: finished parsing /etc/pacman.d/mirrorlist
[13:35:43] config: finished parsing /etc/pacman.conf
[13:35:43] setting up libalpm
[13:35:43] checking local db /tmp/kalu-6XIDH0
[13:35:43] ..folder found, getting dbpath
[13:35:43] same dbpath (/var/lib/pacman), re-using
[13:35:43] keeping current /tmp/kalu-6XIDH0/sync/extra.db
[13:35:43] keeping current /tmp/kalu-6XIDH0/sync/core.db
[13:35:43] keeping current /tmp/kalu-6XIDH0/sync/multilib.db
[13:35:43] keeping current /tmp/kalu-6XIDH0/sync/community.db
[13:35:43] register core
[13:35:43] add server http://mirror.internode.on.net/pub/archlinux/core/os/x86_64 into core
[13:35:43] add server http://ftp.iinet.net.au/pub/archlinux/core/os/x86_64 into core
[13:35:43] add server http://ftp.swin.edu.au/archlinux/core/os/x86_64 into core
[13:35:43] add server https://syd.mirror.rackspace.com/archlinux/core/os/x86_64 into core
[13:35:43] add server http://syd.mirror.rackspace.com/archlinux/core/os/x86_64 into core
[13:35:43] add server http://archlinux.melbourneitmirror.net/core/os/x86_64 into core
[13:35:43] add server https://archlinux.mirror.digitalpacific.com.au/core/os/x86_64 into core
[13:35:43] add server http://archlinux.mirror.digitalpacific.com.au/core/os/x86_64 into core
[13:35:43] add server https://mirror.aarnet.edu.au/pub/archlinux/core/os/x86_64 into core
[13:35:43] register extra
[13:35:43] add server http://mirror.internode.on.net/pub/archlinux/extra/os/x86_64 into extra
[13:35:43] add server http://ftp.iinet.net.au/pub/archlinux/extra/os/x86_64 into extra
[13:35:43] add server http://ftp.swin.edu.au/archlinux/extra/os/x86_64 into extra
[13:35:43] add server https://syd.mirror.rackspace.com/archlinux/extra/os/x86_64 into extra
[13:35:43] add server http://syd.mirror.rackspace.com/archlinux/extra/os/x86_64 into extra
[13:35:43] add server http://archlinux.melbourneitmirror.net/extra/os/x86_64 into extra
[13:35:43] add server https://archlinux.mirror.digitalpacific.com.au/extra/os/x86_64 into extra
[13:35:43] add server http://archlinux.mirror.digitalpacific.com.au/extra/os/x86_64 into extra
[13:35:43] add server https://mirror.aarnet.edu.au/pub/archlinux/extra/os/x86_64 into extra
[13:35:43] register community
[13:35:43] add server http://mirror.internode.on.net/pub/archlinux/community/os/x86_64 into community
[13:35:43] add server http://ftp.iinet.net.au/pub/archlinux/community/os/x86_64 into community
[13:35:43] add server http://ftp.swin.edu.au/archlinux/community/os/x86_64 into community
[13:35:43] add server https://syd.mirror.rackspace.com/archlinux/community/os/x86_64 into community
[13:35:43] add server http://syd.mirror.rackspace.com/archlinux/community/os/x86_64 into community
[13:35:43] add server http://archlinux.melbourneitmirror.net/community/os/x86_64 into community
[13:35:43] add server https://archlinux.mirror.digitalpacific.com.au/community/os/x86_64 into community
[13:35:43] add server http://archlinux.mirror.digitalpacific.com.au/community/os/x86_64 into community
[13:35:43] add server https://mirror.aarnet.edu.au/pub/archlinux/community/os/x86_64 into community
[13:35:43] register multilib
[13:35:43] add server http://mirror.internode.on.net/pub/archlinux/multilib/os/x86_64 into multilib
[13:35:43] add server http://ftp.iinet.net.au/pub/archlinux/multilib/os/x86_64 into multilib
[13:35:43] add server http://ftp.swin.edu.au/archlinux/multilib/os/x86_64 into multilib
[13:35:43] add server https://syd.mirror.rackspace.com/archlinux/multilib/os/x86_64 into multilib
[13:35:43] add server http://syd.mirror.rackspace.com/archlinux/multilib/os/x86_64 into multilib
[13:35:43] add server http://archlinux.melbourneitmirror.net/multilib/os/x86_64 into multilib
[13:35:43] add server https://archlinux.mirror.digitalpacific.com.au/multilib/os/x86_64 into multilib
[13:35:43] add server http://archlinux.mirror.digitalpacific.com.au/multilib/os/x86_64 into multilib
[13:35:43] add server https://mirror.aarnet.edu.au/pub/archlinux/multilib/os/x86_64 into multilib
[13:35:43] core is up to date

(kalu:1711): Gtk-CRITICAL **: 13:35:43.881: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed
[13:35:44] extra was updated
[13:35:44] community is up to date
[13:35:44] multilib is up to date

(kalu:1711): Gtk-CRITICAL **: 13:35:44.302: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed
[13:35:44] looking for AUR updates
[13:35:44] downloading https://aur.archlinux.org/rpc/?v=5&type=info&arg<list of AUR packages>

(kalu:1711): Gtk-CRITICAL **: 13:35:44.724: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed

(kalu:1711): Gtk-CRITICAL **: 13:35:45.144: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed

(kalu:1711): Gtk-CRITICAL **: 13:35:45.565: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed
[13:35:45] downloaded 31280 bytes
[13:35:45] parsing json
[13:35:45] got 52 results
[13:35:45] downloading https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=<list of AUR packages>

(kalu:1711): Gtk-CRITICAL **: 13:35:45.986: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed

(kalu:1711): Gtk-CRITICAL **: 13:35:46.406: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed


<2–3 errors every second>


(kalu:1711): Gtk-CRITICAL **: 13:49:47.449: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed

(kalu:1711): Gtk-CRITICAL **: 13:55:27.137: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed


<2–3 errors every second>


(kalu:1711): Gtk-CRITICAL **: 13:58:48.836: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed
[13:58:48] adding new notif (Unable to check for AUR packages) to last_notifs
[13:58:48] showing notif: Unable to check for AUR packages
OpenSSL SSL_read: Connection timed out, errno 110
--- EOF ---
[13:58:48] new notification: using kalu's icon
[13:58:48] looking for Watched AUR updates
[13:58:48] downloading https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=kalu&arg[]=phyml

(kalu:1711): Gtk-CRITICAL **: 13:58:49.257: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed

(kalu:1711): Gtk-CRITICAL **: 13:58:49.678: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed
[13:58:50] downloaded 1078 bytes
[13:58:50] parsing json
[13:58:50] got 2 results
[13:58:50] state non-busy: disable switch icons
[13:58:50] state non-busy: next auto-checks in 3600 seconds

(kalu:1711): Gtk-CRITICAL **: 13:58:50.092: gtk_status_icon_set_from_icon_name: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed
```

A few things to note.

* Kalu didn't actually stall indefinitely here, and the timeout seemed to reset it at 13:58:48. 
* There was a six-minute gap in the GTK errors, from 13:49:47.449 to 13:55:27.137. This is when the computer automatically suspended.
* Hence, the timeout occurred ~3.5 minutes after resuming from suspension.
* This means that Kalu stalled for 23 minutes in total, from 13:35:45. This includes the first duration up to the automatic suspension of 14 minutes.
